### ISSUE TITLE
Add BASE & missing namespaces

### ISSUE THREAD

**Issue by ktk** [mchlrch/experimental-rmdsl#1]
Currently there is no way to define a `BASE` for the output so manual editing is needed. Also at least `xsd` prefix is missing in the prefix definition.

**Comment by mchlrch** [comment]
For R2RML, the base IRI is part of the execution context for an R2RML processor. The base IRI is not part of the R2RML mapping itself.

https://www.w3.org/TR/r2rml/#dfn-base-iri
